table 'Age Range'
	lineageTag: 8ebf1322-9750-4683-a17b-9395240f88cd

	column 'Age Range'
		dataType: string
		lineageTag: 9b1cacd5-acce-498b-b9c0-14602b46027c
		summarizeBy: none
		sourceColumn: Age Range

		annotation SummarizationSetBy = Automatic

	column 'Age index'
		dataType: int64
		formatString: 0
		lineageTag: 3ae0ac4e-cf68-4f3a-85cf-fcff1154cfaf
		summarizeBy: none
		sourceColumn: Age index

		annotation SummarizationSetBy = Automatic

	partition 'Age Range' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wiik1MDBONrRQitWJVjK0UCjJVzAyBXOMzEAcYwjHGMwxgXBMwBxTCMcUzDGDcMCmpYI4sQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Age Range" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Age Range", type text}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Age index"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

