table 'RepayStatus Range'
	lineageTag: 10e3d399-af40-4e87-b4d0-727283649032

	column 'RepayStatus Index'
		dataType: int64
		formatString: 0
		lineageTag: 9177838b-a4bf-4e34-985e-df4dffa7f2e7
		summarizeBy: sum
		sourceColumn: RepayStatus Index

		annotation SummarizationSetBy = Automatic

	column 'RepayStatus Range'
		dataType: string
		lineageTag: 76b9621a-f8f0-47e8-816b-999a6bd7fd7a
		summarizeBy: none
		sourceColumn: RepayStatus Range

		annotation SummarizationSetBy = Automatic

	partition 'RepayStatus Range' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci9KTE5VCEgtysxPUYrViVYKSMyEMAwVSvIVjA3AbGMwxwzCMQNzLCEcSzDH0ALCA9LaSrGxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"DPD Range" = _t]),
				    #"Renamed Columns1" = Table.RenameColumns(Source,{{"DPD Range", "RepayStatus Range"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns1", "Index", 1, 1, Int64.Type),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Index",{{"RepayStatus Range", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Index", "RepayStatus Index"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

